version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nginx_logs_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  log-monitor:
    build: ./src  
    container_name: nginx_log_monitor
    env_file: .env
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - ./src:/app  
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped